import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-c", "tmux new-session -A -s main"]
[hints]
alphabet = "ntesiroagmplfuwy"

[[hints.enabled]]
regex = '''(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)
              [^\u0000-\u001F\u007F-\u009F<>" {}\\^⟨⟩`]+'''
hyperlinks = true
command = "xdg-open"
post_processing = true

[hints.enabled.mouse]
enabled = true
mods = "None"

[hints.enabled.binding]
key = "L"
mods = "Alt"

[window]
opacity = 0.98
blur = true
startup_mode = "Maximized"
dynamic_title = false
decorations = "Buttonless"

[font.normal]
# family = "Firacode NerdFont Mono"
# style = "SemiBold"
family = "MesloLGS NerdFont"
style = "Regular"

[cursor]
style = {shape="Beam", blinking="Never"}
